### ISSUE TITLE
lnurl-auth not working on Zeus for Android

### ISSUE THREAD

**Issue by saucecoat** [fiatjaf/awesome-lnurl#52]
The lnurl-auth function doesn't seem to work on the Zeus wallet for Android. 
Tested it on [https://lightninglogin.live/login](https://lightninglogin.live/login) and authentification failed.

**Comment by fiatjaf** [comment]
Please open an issue on the Zeus repository, or go to https://t.me/zeusln.

**Comment by saucecoat** [comment]
I just wanted to let you know that the table is incorrect, if Zeus can't handle lnurl-auth.
