### ISSUE TITLE
What does 💬 mean?

### ISSUE THREAD

**Issue by torkelrogstad** [fiatjaf/awesome-lnurl#57]
I see that there's a 💬 icon next to a few wallets in the compatability table. What does this mean?

**Comment by fiatjaf** [comment]
It means https://github.com/fiatjaf/lnurl-rfc/blob/luds/12.md, comments.

**Comment by fiatjaf** [comment]
Also join https://t.me/lnurl where all your other doubts will will be clarified instantly.
