### ISSUE TITLE
No cent amounts allowed in my lnurl-pay

### ISSUE THREAD

**Issue by thmsmullee** [fiatjaf/awesome-lnurl#59]
If I create a new static qr-code pay link I can't get it to work to put in 5,50€. 
I tried 5,50 and also 5.50
Doesn't work
Thanks

**Comment by fiatjaf** [comment]
I think you may be talking about some specific software. If that is the case, please complain on their support channels. Otherwise please clarify.

**Comment by thmsmullee** [comment]
![lnurl](https://user-images.githubusercontent.com/97939631/165340031-0ad35c2f-e257-4c68-ab69-1f2c561eb2f3.png)

I can't put the amount to 5.5 €

**Comment by arcbtc** [comment]
Thats lnbits, you can post here https://github.com/lnbits/lnbits-legend
Short answer is, its currently not possible in the extension, for now denominate in sats, and we will take a look at adding float support for fiat denominated

**Comment by thmsmullee** [comment]
On my side it says: 
![awesome](https://user-images.githubusercontent.com/97939631/165592335-942d5891-85e6-4753-bb28-c920ee0b629c.png)

But how did this happen ? How is this possible ? Its on the awesome-lnurl website!

![FEK3Lg7X0AIoyOj](https://user-images.githubusercontent.com/97939631/165592459-bd79f731-6a33-475e-b178-eb121fec1d9b.jpg)
