### ISSUE TITLE
Add coin train - live demo

### ISSUE THREAD

**Issue by satoshkey** [fiatjaf/awesome-lnurl#60]
**Send the train on a journey ! [Live demo](https://www.satoshkey.com/).**
Thanks in advance for considering to add satoshkey payToIo to the list of awesome lnurl things !

https://user-images.githubusercontent.com/106029426/174245385-13841fde-b735-4e70-84fd-c16b56abc667.mp4

**Comment by fiatjaf** [comment]
This is cool, but how is it using LNURL?

**Comment by fiatjaf** [comment]
I see you have a server that triggers stuff on an electronic board. I suggest that you turn the `executecommand` endpoints into lnurlpay-capable HTTP endpoints, so users can print static QR codes that trigger the device.

**Comment by satoshkey** [comment]
Many thanks for your suggestion! We find it handy for users to print the static QR code from e.g. LNbits LNURLp extension, like in the demo. The configured webhook URL is then processed by the device. This minimizes the attack surface and keeps our server simple and generic. We come from replacing traditional coin machines with crypto currency payments and LNURL made it a lot easier! Do you see an advantage of exposing lnurlpay-capable endpoints from the device over processing the webhook ? thanks in advance.

**Comment by fiatjaf** [comment]
No, I think your setup is great as it is.

The problem is that the video doesn't show the scanning of the static QR code in action!

**Comment by satoshkey** [comment]
Agree. We'll change that.

**Comment by fiatjaf** [comment]
Did you post this to Twitter? So I can retweet it.

**Comment by satoshkey** [comment]
Much appreciated. [Tweet](https://twitter.com/satoshkey/status/1538508657910226944?s=20&t=S_UZIgFQlnpgVqjfEsf7uA).

and the updated video.


https://user-images.githubusercontent.com/106029426/174483989-cb0b4e67-81ac-4bf6-98a3-8e9bd9bf2f85.mp4

**Comment by fiatjaf** [comment]
Awesome, thanks!

**Comment by fiatjaf** [comment]
By the way, the link on https://satoshkey.com/ doesn't point to `lightning:LNURL1...` as it should. Instead it points to `https://legend.lnbits,com/...` and so it doesn't work on wallets.
